name: Java CI with Maven

on:
  workflow_run:
    workflows: ["CodeQL Java Analysis"]  # Déclenche après la fin de CodeQL
    types:
      - completed  # S'exécute après la fin du premier workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file refquiz-api/pom.xml

      - name: Run unit tests
        run: mvn test --file refquiz-api/pom.xml
